"""Initial migration

Revision ID: 3df7e1e5fa16
Revises: db4cc01a42d6
Create Date: 2024-10-17 08:25:44.843800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df7e1e5fa16'
down_revision: Union[str, None] = 'db4cc01a42d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('image_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'image_id')
    # ### end Alembic commands ###
