"""Initial migration

Revision ID: 6488204d0a25
Revises: aecfbf4a8dee
Create Date: 2024-10-17 22:16:52.936179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6488204d0a25'
down_revision: Union[str, None] = 'aecfbf4a8dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('specialist_id', sa.Uuid(), nullable=False),
    sa.Column('order_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
