"""Initial migration

Revision ID: aecfbf4a8dee
Revises: 85ceacdb9065
Create Date: 2024-10-17 21:13:39.570733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aecfbf4a8dee'
down_revision: Union[str, None] = '85ceacdb9065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialist_avatars', sa.Column('specialist_id', sa.Uuid(), nullable=False))
    op.add_column('specialist_avatars', sa.Column('avatar', sa.LargeBinary(), nullable=False))
    op.drop_constraint('specialist_avatars_specialist_avatar_key', 'specialist_avatars', type_='unique')
    op.create_unique_constraint(None, 'specialist_avatars', ['specialist_id'])
    op.drop_column('specialist_avatars', 'image')
    op.drop_column('specialist_avatars', 'specialist_avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialist_avatars', sa.Column('specialist_avatar', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('specialist_avatars', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'specialist_avatars', type_='unique')
    op.create_unique_constraint('specialist_avatars_specialist_avatar_key', 'specialist_avatars', ['specialist_avatar'])
    op.drop_column('specialist_avatars', 'avatar')
    op.drop_column('specialist_avatars', 'specialist_id')
    # ### end Alembic commands ###
