"""add column last_reset_attempts , reset_attempts, code_expiry_time

Revision ID: 1abfc23d96bc
Revises: 9aa12300eaf5
Create Date: 2024-12-03 17:30:51.931724

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1abfc23d96bc"
down_revision: Union[str, None] = "9aa12300eaf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("code_expiry_time", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("reset_attempts", sa.Integer(), nullable=True))
    op.add_column(
        "user", sa.Column("last_reset_attempts", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###
    op.execute('UPDATE "user" SET reset_attempts = 0 WHERE reset_attempts IS NULL')

    # Теперь изменяем столбец на NOT NULL
    op.alter_column(
        "user", "reset_attempts", existing_type=sa.Integer(), nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_reset_attempts")
    op.drop_column("user", "reset_attempts")
    op.drop_column("user", "code_expiry_time")
    # ### end Alembic commands ###
