"""Add role in user

Revision ID: 81a0dcca08b1
Revises: dc77997e49a7
Create Date: 2024-11-19 00:01:10.123440

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81a0dcca08b1"
down_revision: Union[str, None] = "dc77997e49a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("role", sa.String(), nullable=False, server_default="user")
    )
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column("role", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    # ### end Alembic commands ###
