"""Second db

Revision ID: d08a919621ab
Revises: 19e23c76516a
Create Date: 2024-11-26 19:02:24.940703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08a919621ab'
down_revision: Union[str, None] = '19e23c76516a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'specialist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.drop_column('service', 'image')
    op.create_index(op.f('ix_specialist_id'), 'specialist', ['id'], unique=False)
    op.drop_column('specialist', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialist', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_specialist_id'), table_name='specialist')
    op.add_column('service', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.alter_column('order', 'specialist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
