services:
  specialist-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: specialist-app
    ports:
      - "8001:8001"
    command: sh -c "alembic upgrade head && uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8001"
    env_file:
      - .env
    depends_on:
      - redis
      - testdb
      - db
    volumes:
      - ../specialists_service/:/specialists_service/
    networks:
      - backend

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
      PGPORT: ${APP_CONFIG__DB__PORT}
    ports:
      - "${APP_CONFIG__DB__PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "${APP_CONFIG__REDIS__PORT}:6380"
    command: --port 6380
    expose:
      - "6380"
    networks:
      - backend

  testdb:
    image: postgres:17
    environment:
      POSTGRES_DB: ${APP_CONFIG__TESTDB__NAME}
      POSTGRES_USER: ${APP_CONFIG__TESTDB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__TESTDB__PASSWORD}
      PGPORT: ${APP_CONFIG__TESTDB__PORT}
    ports:
      - ${APP_CONFIG__TESTDB__PORT}:5432
    env_file:
      - .env
    networks:
      - backend

volumes:
  postgres_data2:

networks:
  backend:
    external: true
