"""Database revision2

Revision ID: 6b0abb195207
Revises: f384b144744c
Create Date: 2024-10-20 20:58:07.874487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0abb195207'
down_revision: Union[str, None] = 'f384b144744c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('service_id', sa.Integer(), nullable=True))
    op.drop_constraint('orders_order_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'services', ['service_id'], ['id'])
    op.drop_column('orders', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_order_id_fkey', 'orders', 'orders', ['order_id'], ['id'])
    op.drop_column('orders', 'service_id')
    # ### end Alembic commands ###
