services:
  service-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-app
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    depends_on:
      - redis
      - services_testdb
      - servicesdb
    volumes:
      - ../services_service/:/services_service/
    networks:
      - backend

  servicesdb:
    image: postgres:17
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
      PGPORT: ${APP_CONFIG__DB__PORT}
    ports:
      - "${APP_CONFIG__DB__PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "${APP_CONFIG__REDIS__PORT}:6379"
    networks:
      - backend

  services_testdb:
    image: postgres:17
    environment:
      POSTGRES_DB: ${APP_CONFIG__TESTDB__NAME}
      POSTGRES_USER: ${APP_CONFIG__TESTDB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__TESTDB__PASSWORD}
      PGPORT: ${APP_CONFIG__TESTDB__PORT}
    ports:
      - "${APP_CONFIG__TESTDB__PORT}:5432"
    env_file:
      - .env
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    external: true
